language: cpp
cache: apt
os:
- linux
compiler:
- gcc
- clang
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ./install_deps.sh; fi
script:
- "./make.sh"
notifications:
  slack:
    secure: biLc1upxAuvnKJCNtvhnor8tAiqnydBPFm4yL2mDOq6AULKDpaipcnRrEVBEGSR2/DnIpZ25tUZ5fkl/HYExSJfZ5cAGypUhT53ER257BmQbqOEE/WC2ZCkScgIOopgPE8spaD+5xMo4CLHbnKUJ6Hu/1PMtH91GI6M1upyXa70=
